### ISSUE TITLE
Default hidden=True in dir2page

### ISSUE THREAD

**Issue by guyhoffman** [dsavransky/grading#7]
hidden should default to True as promised in the docstring, and as makes sense. 

https://github.com/dsavransky/grading/blob/0d5b01af029d6b1a32ab11e847a0bd44afe2a113/cornellGrading/cornellGrading.py#L1716

I thought it's not worth to do a whole pull request for that change and it can be put into the next real change.

**Comment by dsavransky** [comment]
Closed by v2.3.1
